name: Deploy to Cloudflare Workers

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/deploy.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "wrangler.toml"
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Worker Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}